# creation of the level

map = [
    "           x    x   ",
    "       x            ",
    "                    ",
    "  x             x   ",
    "                    ",
    "                    ",
    "        x           ",
    "                    ",
    "                    ",
    "   x      x         ",
    "                    ",
    "                    ",
    "            x       ",
    "                    ",
    "                    "
    "  x             x   ",
    "                    ",
    "                    ",
    "        x       x   ",
    "                    ",
    "                    ",
    " x             x    ",
    "                    ",
    "                    ",
    "          x         ",
    "                    ",
    "                    ",
    "   x     x      x   ",
    "                    ",
    "                    "
    "      x           x ",
    "                    ",
    "                    ",
    "          x         ",
    "                    ",
    "                    ",
    "   x           x    ",
    "                    ",
    "                    ",
    "   x      x       x ",
    "                    ",
    "                    ",
    "   x            x   ",
    "                    ",
    "                    ",
    "      x             ",
    "                    ",
    "                    ",
    " x         x        ",
    "                    ",
    "                    ",
    "     x            x ",
    "                    ",
    "                    ",
    "               x    ",
    "                    ",
    "                    ",
    "   x      x         ",
    "                    ",
    "                    ",
    "            x       ",
    "                    ",
    "                    ",
    "     x            x ",
    "                    ",
    "                    ",
    "    x               ",
    "                    ",
    "                    ",
    "       x       x    ",
    "                    ",
    "                    ",
    "  x                 ",
    "                    ",
    "                    ",
    "        x       x   ",
    "                    ",
    "                    ",
    "x   x               ",
    "                    ",
    "                    ",
    "       x           x",
    "                    ",
    "                    ",
    "    x          x    ",
    "                    ",
    "         p          ",
    "         x          "]

# setting varible settings

tile_size = 64
screen_width = 1400
screen_height = 725
fps = 60

